# Typical usage:  climate run g++ main.cpp

[app]
name = "g++"
description = "GNU C++ compiler"
license = "GPL-3.0-or-later"

[image]
reference = "docker.io/library/gcc:latest"

[run]
entrypoint = "g++"
